Branch 1
javdad/Budgetify pull request #1
Opened 2022-03-18 14:35 UTC by javdad

Created new project. HW1-2-3 Included. Could't split them into different PR's, honestly don't know how. Still working on and will add more code. Hope for your feedback.

2022-03-21 07:37 UTC, AudriusBaltusis commented
Postman collection is missing

2022-03-21 07:38 UTC, AudriusBaltusis requested changes

2022-03-21 07:38 UTC, AudriusBaltusis commented on models/account.js
> +	user: {
`userId`

2022-03-21 07:38 UTC, AudriusBaltusis commented on controllers/categoriesControl.js
> +			res.send("Create new category");
You should use DB for all routes

2022-03-21 07:38 UTC, AudriusBaltusis commented on routes/expenses.js
> +router.get("/", controller.getExpense);
Authorization is not required for these routes?

2022-03-21 09:00 UTC, javdad commented
> Postman collection is missing

I have Postman collection. Should I share the link?

2022-03-21 10:35 UTC, AudriusBaltusis commented
> > Postman collection is missing
> 
> I have Postman collection. Should I share the link?

you have to commit it to repository

2022-03-24 11:45 UTC, AudriusBaltusis approved these changes

2022-03-24 18:51 UTC, merged