Front-end HW-4
javdad/Budgetify pull request #6
Opened 2022-04-10 22:33 UTC by javdad

backend:
removed expenses and incomes and add transactions. Changed and fixed some parts of code.

frontend:
added accounts, categories, transactions components and linked to the server. Statistics and admin page will be added.
fixed routes, added some styles. Working on styles. Most of 'any' types will be changed.

2022-04-11 12:20 UTC, AudriusBaltusis requested changes

2022-04-11 12:20 UTC, AudriusBaltusis commented on Client/src/app/app-routing.module.ts
> +    {path: 'main', component: MainLayoutComponent, canActivate: [AuthGuard], children: [
Code formatting is awkward. Please use
```
{
  path: 'main',
  component: MainLayoutComponent,
  canActivate: [AuthGuard],
  children: [
    {
      path: '',
      component: SidenavComponent,
      canActivate: [AuthGuard],
      children: [
        { path: '', component: TransactionsComponent },
        { path: 'categories', component: CategoriesComponent },
        { path: 'statistics', component: StatisticsComponent },
      ]
    }
  ]
}
```

2022-04-11 12:20 UTC, AudriusBaltusis commented on Client/src/app/components/account/account.component.ts
> +  @Input() account: any;
`any`

2022-04-11 12:20 UTC, AudriusBaltusis commented on Client/src/app/components/categories/categories.component.ts
> +  categories: any = []
`any`

2022-04-11 12:20 UTC, AudriusBaltusis commented on Client/src/app/components/categories/categories.component.ts
> +    this.category.getCategories().subscribe((categories) => {
You have to unsubscribe, or use `takeUntil()`

2022-04-11 12:20 UTC, AudriusBaltusis commented on Client/src/app/components/statistics/statistics.component.ts
> +  ngOnInit(): void {
Please remove redundant `ngOnInit`

2022-04-11 12:20 UTC, AudriusBaltusis commented on Client/src/app/components/transactions/transaction/transaction.component.ts
> +  @Input() transaction: any;
`any`

2022-04-11 12:20 UTC, AudriusBaltusis commented on Client/src/app/services/account.service.ts
> +  getAccounts() {
Please add return type

2022-04-18 15:23 UTC, javdad commented
I made the requested changes last week. Wanted to ask if you checked them?

2022-04-18 15:30 UTC, javdad commented
I made the requested changes last week. Wanted to ask if you checked them?

2022-04-19 17:03 UTC, AudriusBaltusis approved these changes

2022-04-19 20:25 UTC, merged